<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "searchbar"
 *
 * Auto generated by Extension Builder 2016-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Universal Search Bar',
	'description' => ' A Search Bar \"wrapper\", to access other existing search engines',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);