<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-06-24 17:46

$extensionPath = t3lib_extMgm::extPath('searchbar');
$extensionClassesPath = t3lib_extMgm::extPath('searchbar') . 'Classes/';
return array(
	'tx_searchbar_functions_field' => $extensionClassesPath . 'class.tx_searchbar_functions_field.php',
	'tx_searchbar_ip' => $extensionClassesPath . 'class.tx_searchbar_ip.php',
	'tx_searchbar_pi1' => $extensionPath . 'pi1/class.tx_searchbar_pi1.php',
	'tx_searchbar_pi1_wizicon' => $extensionPath . 'pi1/class.tx_searchbar_pi1_wizicon.php',
);